### ISSUE TITLE
lorem.paragraph(paragraph_length) Def is not receiving any parameter

### ISSUE THREAD

**Issue by ftalamo** [TheAbhijeet/lorem_text#139]

**Comment by TheAbhijeet** [comment]
Can you explain more `lorem.paragraph()` seems to work. 

> >>> **lorem.paragraphs(1)**
'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
>>> **lorem.paragraphs(3)**
'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nUllam aspernatur nam debitis labore accusantium, pariatur quae voluptas quas distinctio assumenda magnam a nobis maxime, labore asperiores amet consequatur distinctio repudiandae harum corporis iure reiciendis, fuga impedit culpa praesentium odit suscipit animi optio, nam perferendis ut eaque quis consectetur quo? Eius facilis repudiandae id officia laborum est odit magni, eveniet magnam eius repellendus vel quaerat laudantium?\nCorporis ipsa sed reiciendis itaque commodi soluta tempore facilis, quia dolorem dolore quidem a magni repellendus sit libero animi inventore quae, facilis qui nisi enim explicabo libero dolorem, officiis aliquid porro beatae fuga quod at aperiam libero omnis ipsam? Rem quidem molestias in assumenda, voluptates molestiae nobis error enim doloremque neque magnam consectetur eos velit? Consequatur minima fuga saepe harum repellat fugit, ipsum repudiandae qui, delectus quisquam quam accusamus sint perferendis minus quia quos deserunt enim reiciendis, ducimus earum corporis placeat accusantium distinctio aspernatur beatae nemo in porro maiores, animi voluptates libero. Incidunt neque quo hic soluta consequatur in, deleniti aut voluptas laborum consectetur consequuntur sapiente magnam quae dolorem iusto cupiditate, exercitationem nulla rem voluptate dolores adipisci?'
